name: test go package

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: install gin
        run:
          go mod download
      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v ./...

